# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

sudo: false

addons:
  apt:
    packages:
        # Requirements for NetPyNE & libNeuroML
    - python-tk
    - python-lxml
    - python-matplotlib 
    

language: python
python: 2.7

 
virtualenv:
system_site_packages: true

env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_NetPyNE
    - OMV_ENGINE=jNeuroML_validate
    - OMV_ENGINE=jNeuroML_validatev1

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all -V
    - pwd
    - ls -al
    - ls -al neuroConstruct/generatedNeuroML2
    
    
    
    

