
//  ******************************************************
// 
//     File generated by: neuroConstruct v1.7.0
// 
//  ******************************************************


//////////////////////////////////////////////////////////////////////
//             ****  NOTE  ****
//   Some of the channel mechanisms in this cell have some of their internal
//   parameters changed after initialisation. This is not possible to specify
//   in a *.p file, and so this file should not be used on its own for this cell,
//   but in conjunction with the parameter changes in the main file after the readcell command.
//////////////////////////////////////////////////////////////////////

*absolute
*cartesian
*asymmetric

*set_global	         RA 2.0  // using: Units[GENESIS_SI_specAxialResistance, symbol: ohm m]

*set_global	         CM 0.0284   // using: Units[GENESIS_SI_specificCapacitance, symbol: F m-2]

*set_global	         RM	0.3333333  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m²]

*set_global	         EREST_ACT	-0.065  // using: Units[GENESIS_SI_voltage, symbol: V]

*set_compt_param     ELEAK	-0.0594  // using: Units[GENESIS_SI_voltage, symbol: V]

*compt /library/compartment

// NOTE: readcell usually assumes SI units (meters, seconds, ohms) above and lengths (below)
// in micrometers. If we use physiological units above, the lengths below will appear quite high


// Cell mechanism: LeakConductance_pyr (density: 1.420051E-9 mS um^-2, e = -66.0)
// Cell mechanism: Ca_conc (density: 0.0 mS um^-2)
// Cell mechanism: Ca_pyr (density: 1.0E-7 mS um^-2)
// Cell mechanism: Kahp_pyr (density: 2.5E-8 mS um^-2)
// Cell mechanism: Kdr_pyr (density: 8.0E-7 mS um^-2)
// Cell mechanism: Na_pyr (density: 1.2E-6 mS um^-2)
*set_compt_param     ELEAK -0.066  // using: Units[GENESIS_SI_voltage, symbol: V]
*set_compt_param     RM 0.7042001  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m²]


*double_endpoint
soma none 0 0 0 0 17 0 23 Ca_conc -1.4166824E24 Ca_pyr 100 Kahp_pyr 25 Kdr_pyr 800 Na_pyr 1200 
*double_endpoint_off

// Cell mechanism: LeakConductance_pyr (density: 1.420051E-9 mS um^-2, e = -66.0)
apical0 soma 0 77 0 6 

// Cell mechanism: LeakConductance_pyr (density: 1.420051E-9 mS um^-2, e = -66.0)
apical2 apical0 0 477 0 4.4 

// Cell mechanism: LeakConductance_pyr (density: 1.420051E-9 mS um^-2, e = -66.0)
apical3 apical2 0 877 0 2.9 

// Cell mechanism: LeakConductance_pyr (density: 1.420051E-9 mS um^-2, e = -66.0)
apical4 apical3 0 1127 0 2 

// Cell mechanism: LeakConductance_pyr (density: 1.420051E-9 mS um^-2, e = -66.0)
apical1 apical0 -150 77 0 3 

// Cell mechanism: LeakConductance_pyr (density: 1.420051E-9 mS um^-2, e = -66.0)
*double_endpoint
basal0 soma 0 0 0 0 -50 0 4 
*double_endpoint_off

// Cell mechanism: LeakConductance_pyr (density: 1.420051E-9 mS um^-2, e = -66.0)
basal1 basal0 106.07 -156.07 0 5 

// Cell mechanism: LeakConductance_pyr (density: 1.420051E-9 mS um^-2, e = -66.0)
basal2 basal0 -106.07 -156.07 0 5 

